pipeline {
    
    agent any
    
    stages {
      stage('build') {
         steps {
            dir("myindiaflight") {
                sh "docker build -t mif-staging ."
            }
         }
      }
    }
    post {
        always {
            
            emailext (
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
                to: '$DEFAULT_RECIPIENTS',
                recipientProviders: [ requestor() ],
                subject: "${currentBuild.currentResult}: Job ${env.JOB_NAME}"
            )
        }
    }
    
}
